# -*- coding: utf-8 -*-
"""DataAnalysis practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9g61C8k9FmJgHkSdUMwerg2TLEsUg7V
"""

# Importing the libraries
import pandas as pd # to use csv files
import numpy as np # for mathematical calculation
import matplotlib.pyplot as plt # for data visualization
# visualization
import seaborn as sns # using mathplot library for data visualization
# Importing the dataset
ds=pd.read_csv("student_attendance.csv")
# list of first five rows
ds.head()



ds.tail()

## checking info of the dataset
ds.info()
## by checking info we can read the null values of the dataset

# to check the mathematical terms or to get the better understanding of dataset
ds.describe()

# to check the unique values in the dataset
ds.nunique()

#check for missing values
ds.isnull().sum()

## checking the value counts of WEATHER
ds["Weather"].value_counts()
#there are no missing data

# checking the value count of temperature
ds["Temperature"].value_counts()
# there is not missing data also the datatyoe is int64

sns.pairplot(ds)

# Gender wise customer distribution
attendance_distribution = ds["Attendance"].value_counts()
plt.pie(attendance_distribution, labels=attendance_distribution.index,
autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightcoral'])
plt.title('Attendance wise student Distribution')
plt.show()