# -*- coding: utf-8 -*-
"""World population.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eaj0R2-RTVP_mGZslZvDTZtlZ47o5LQX
"""

# Importing the libraries
import pandas as pd # to use csv files
import numpy as np # for mathematical calculation
import matplotlib.pyplot as plt # for data visualization
# visualization
import seaborn as sns # using mathplot library for data visualization
# Importing the dataset
ds=pd.read_csv("world_population_data.csv")
# list of first five rows
ds.head()

ds.tail()

#check for missing values
ds.isnull().sum()
## no missing data found

# checking the value count of country
ds["country"].value_counts()
# there is not missing data it has 234 data also the datatype is int64

sns.pairplot(ds)

sns.countplot(x="continent", data=ds)